### ISSUE TITLE
Is it possible to convert custom blots?

### ISSUE THREAD

**Issue by DmitrySkripkin** [nozer/quill-delta-to-html#1]
I'm not sure, but I don't see any of my custom blots in `beforeRender`.

**Comment by nozer** [comment]
I don't think so as I have only taken into account format options explained on this page https://quilljs.com/docs/formats/

**Comment by DmitrySkripkin** [comment]
Ok, I've just tried to fork this repo to add my custom blots myself. There is no problem, that is rather easy. It's good idea to keep it simple.
Thank you for quick answer.
P.S. Nice repo. Saved me another week.

**Comment by nozer** [comment]
Thank you. You are welcome.
