### ISSUE TITLE
adding extra new lines when dealing with code-block

### ISSUE THREAD

**Issue by csbenjamin** [nozer/quill-delta-to-html#10]
When using the delta:

    [
      {
        "insert": "handler(range: { index: Number, length: Number },"
      },
      {
        "attributes": {
          "code-block": true
        },
        "insert": "\n"
      },
      {
        "insert": "        oldRange: { index: Number, length: Number },"
      },
      {
        "attributes": {
          "code-block": true
        },
        "insert": "\n"
      },
      {
        "insert": "        source: String)"
      },
      {
        "attributes": {
          "code-block": true
        },
        "insert": "\n"
      }
    ]

the expected behavior is to get something like:

    <pre>handler(range: { index: Number, length: Number },
            oldRange: { index: Number, length: Number },
            source: String)
    </pre>

but instead we are getting this:

    <pre>handler(range: { index: Number, length: Number },
    
    
            oldRange: { index: Number, length: Number },
    
    
            source: String)</pre>

Am I missing something?

**Comment by nozer** [comment]
I will look at it during weekend(tomorrow)

**Comment by nozer** [comment]
Fixed and pushed as release v0.5.7

**Comment by csbenjamin** [comment]
Thanks
