### ISSUE TITLE
new lines to br or p

### ISSUE THREAD

**Issue by uptownhr** [nozer/quill-delta-to-html#13]
i'm comparing a simple ops entry of 

`{{employee.profile.first_name}}\ntest\n\ntest\n`

Using quill the editor converts the `\n` to paragraphs while `quill-delta-to-html` lib is converting to `<br>` Is this by design? Is there an option to change behavior?

**Comment by nozer** [comment]
Yes, by design. All consecutive inline items (those other than header, blockquote, codeblock, video) are wrapped in a `<p>` tag (that can be configured) and all `\n`s are converted to `<br>` tags
