### ISSUE TITLE
Empty Line Between Headings Not Rendered

### ISSUE THREAD

**Issue by homerlex** [nozer/quill-delta-to-html#16]
Use the header toolbar option:
`[{ 'header': [1, 2, false] }]`

Edit a document:
* Add a line of text with "Heading 1"
* Add a blank line under Heading 1
* Add a line under the blank formatted with Heading 2

Notice that quill-delta-to-html did not render a <br/> between the two headings.

See it in action here: https://www.screencast.com/t/1EzZhD3XPvQq

Here is the HTML inside quill:
`<h1>Heading1</h1><p><br></p><h2>Heading2</h2>`

Here is where quill-delta-to-html came up with:
`<h1>Heading1</h1><p></p><h2>Heading2</h2>`

**Comment by nozer** [comment]
Thanks for catching that. Fixed and pushed to tag `v0.7.0`

**Comment by homerlex** [comment]
@nozer - perfect, thank you.
