### ISSUE TITLE
converter.renderCustomWith doesn't return width attribute in callback 

### ISSUE THREAD

**Issue by parthdesai93** [nozer/quill-delta-to-html#17]
Hey, first of all thanks for this library. Saved me a week's worth of work. :)

I'm trying to render HTML along with custom blot from quill ops object ( which will be saved in db) and width attribute is not being returned for some reason. 

This is my sample ops object.

    let ops = [ 
      {
        insert: 'random Text goes here'
      },
      {
        attributes: { link: 'http://www.link.com' },
        insert: 'http://www.link.com'
      },
      {
        attributes: { width: '600px', height: '807px', someother: 'dadsa' },
        insert: {
          media:
            'https://www.exampleurltomedia.com/id'
        }
      }
    ];
    
    let converter = new QuillDeltaToHtmlConverter(ops, {});
      converter.renderCustomWith(ops => {
        if (ops.insert.type === 'media') {
          console.log('ops', ops);
          let val = ops.insert.value;
          return `<iframe src="${val}" frameborder="none" height=${ops.attributes
            .height} width=${ops.attributes.width}></iframe>`;
        }
    });

The output for `console.log('ops', ops)` looks like this: 
    
    ops DeltaInsertOp {
     insert:
     InsertDataCustom {
       type: 'media',
       value: 'https://www.exampleurltomedia.com/id' 
     },
      attributes: { height: '807px', someothr: 'dadsa' }
    }

If i change `width` to `width1` or anything else it shows up in attributes object. I tried looking at the code but couldn't find where it is stripping the width attribute.

Do let me know if my question is not clear enough.

**Comment by nozer** [comment]
It is a bug; attribute sanitizer for width is expecting only numbers (erroneously). I will fix and push this weekend.

**Comment by parthdesai93** [comment]
If you can point me where to look at in the code, i can try fixing it. Just giving a heads up, I don't know typescript though

**Comment by nozer** [comment]
It is following method in OpAttributeSanitizer. You also need to add tests. 
```
static IsValidSize(size: string) {
      return !!size.match(/^[a-z\-]{1,20}$/i)
   }
```

**Comment by nozer** [comment]
Ok pushed with tag v0.7.1
