### ISSUE TITLE
<br> instead of <p>

### ISSUE THREAD

**Issue by DmitrySkripkin** [nozer/quill-delta-to-html#2]
I have single op delta:
```
{ops: [
  { insert: 'TEST\nTEST\nTEST\nTEST\n' }
]}
```
And I get something like this when I convert:
```
<p>
  TEST
  <br>
  TEST
  <br>
  TEST
</p>
```
But Quill renders this as:
```
<p>TEST</p>
<p>TEST</p>
<p>TEST</p>
```
BTW I was not able to create `<p>` with breaklines here https://quilljs.com/playground/ or in `demo-browser.html`. It's a new paragraph each time I hit enter or paste text with breaklines.

**Comment by nozer** [comment]
That is how I intended it to work (mimicked trix editor in this regard https://trix-editor.org ). Block contents (with same align indent and direction) are also put in one block tag (h*, pre, etc) with `br` tags for new lines. Also, lists are nested as well (inner listed is child of `li`). These are the differences from quill's output.

**Comment by nozer** [comment]
FYI, I am not actively maintaining this; I created dotnet version of it and using that one for my project. If you have questions I can answer but I don't have time to make changes at this point.

**Comment by DmitrySkripkin** [comment]
Got it, no problem. My goal is to generate completely same HTML as Quill does (for inline editing). I can make some changes in my repo then.

**Comment by brianreeve** [comment]
@DmitrySkripkin, I have a similar need. Do you mind sharing your solution?

I have started down a path to accomplish this in a `beforeRender` or `afterRender` event handler to avoid modifications to the source, then share my results with the community. However, if you have something working well already, perhaps I can adapt that.

Thanks!
