### ISSUE TITLE
module import

### ISSUE THREAD

**Issue by valentinbdv** [nozer/quill-delta-to-html#24]
Is it possible to import the QuillDeltaToHtmlConverter constructor in a module base project after installing it with npm?

Thanks, great library!

**Comment by nozer** [comment]
If you are importing to a .ts project, you should do `import QuillDeltaToHtmlConverter = require('quill-delta-to-html');`

If importing to a .js project, then you do `let QuillDeltaToHtmlConverter = require('quill-delta-to-html');`

**Comment by nozer** [comment]
I may have to look into doing an `export default ...` as opposed to `export = ...` that I am doing currently. When exported with `export default ...`, `import x from 'y'` will work; however, when exported with `export = ` syntax, then import must be like `import x = require('y')` from typescript;

**Comment by valentinbdv** [comment]
Ok I didn't know that difference. 
Indeed I think it would be better to just have import x from 'y' as most people will do I guess. 
Or least explain that we have to add the require function in the README so that everybody has the right import from the first time! 

Thanks a lot

**Comment by nozer** [comment]
Will do. Welcome.
