### ISSUE TITLE
Text and some blots are losing values when implementing custom rendering

### ISSUE THREAD

**Issue by highspotjeremy** [nozer/quill-delta-to-html#26]
I've added a `renderCustomWith()` handler to perform rendering of custom blots. I've also added a `beforeRender` to capture certain elements and alter their rendering. The captured elements are lists and contain child blots that are being rendered by invoking a new instance of the converter with the child ops.

When processing the ops, any text and some other blots, such as images, that are encountered are converted into an `InsertDataCustom` object with `type` and `value` attributes set as such: `{ type: "type", value: "<ACTUAL_TYPE>" }` where `<ACTUAL_TYPE>` is the value that was previously reported for the value of the `type` field.

This is relatively trivial to fix for text blots, as the code is designed to treat ordinary strings as text. However, I am trying to use an image custom blot, but because the `value` field is being overwritten by the `type`, the URL to the image is lost. The `attributes` hash retains its former values. Unfortunately, the URL to the image is not included there (nor is the text in the case of a text blot).

This appears to be happening in `InsertOpsConverter.convertInsertVal(insertPropVal)` and seems to happen because there is no `image` field. If I hook into the items and add the `image` field, the problem goes away (for images).

**Comment by nozer** [comment]
Can you give example ops with expected output?

**Comment by highspotjeremy** [comment]
This code *should* repro the issue, but I can't test it at the moment. In `renderCustomWith`, `customOp.insert.type` was coming up as "`type`" in my tests, and `customOp.insert.value` was "`value`".

Renderer:
```javascript
const QuillDeltaToHtmlConverter = require("quill-delta-to-html");
class QuillRenderer extends QuillDeltaToHtmlConverter {
  constructor(ops, config) {
    super(ops, config);

    this.beforeRender(function(groupType, data) {
      switch (groupType) {
        case "list":
          // console.log("List", data);
          // Commenting the next line, since it's not included in the code example
          // return that.renderList(data.items);
        default:
          return false;
      }
    });

    this.renderCustomWith(function(customOp, contextOp) {
      switch (customOp.insert.type) {
        case "image": // Image
          let attrs = {};
          Object.getOwnPropertyNames(customOp.attributes || {}).forEach(a => {
            let v = customOp.attributes[a];
            (a == "class") && v && (v = v.split(/ +/g).filter(c => !c.match(/^ql\-/)).join` `);
            v && (attrs[a] = v);
          });
          let attrsStr = Object.getOwnPropertyNames(attrs).map(a => ` ${encodeURIComponent(a)}="${encodeURIComponent(customOp.attributes[a])}"`).join` `;
          return `<img${attrsStr} src="${encodeURIComponent(customOp.insert.value)}" />`;
        default: // Unrecognized
          return `<script type="text/custom-blot" blot="${customOp.insert.type}">${JSON.stringify(customOp.insert)}</script>`;
      }
    });
  }
}
```

Implementation:
```javascript
// Variable "quill" should be declared and set to the Quill instance
let delta = quill.getContents();
let converter = new QuillRenderer(delta.ops);
var html = converter.convert();
console.log("Converted Quill Delta to HTML", delta, html);
```

**Comment by nozer** [comment]
Can you please provide some sample ops containing your custom blots? I am asking because `renderCustomWith` would never be called with `image` as the value for `customOp.insert.type`. `image` is one of the built-in types for quill(along with formula, video) and not a custom blot. If you showed a sample of your custom blot op, I would be able to understand better. 

Also, please note that format for a custom blot must be like this in the ops array that you pass to converter:
```
[..., {insert: {<name-of-your-custom-blot>: <value-for-custom-blot>}, attributes: {}}, ...]
```
where `name-of-your-custom-blot` is a string that is not one of 'image', 'video', 'formula' and 
`value-for-custom-blot` is an object
