### ISSUE TITLE
`a href="#test"` is converted to `a href="unsafe:#test"`

### ISSUE THREAD

**Issue by dcsaszar** [nozer/quill-delta-to-html#29]
The sanitiser breaks fragment-only links.

### Input
`<a href="#test">`

### Expected output

`<a href="#test">`

### Actual output

`<a href="unsafe:#test">`

**Comment by nozer** [comment]
Fixed it by supporting href values starting with # (I was prefixing all urls that do not start with a known protocol with `unsafe:` ) Tag is v0.9.4

**Comment by dcsaszar** [comment]
Thanks. Unfortunately, I just discovered the next issue, absolute links also break:

`<a href="/1234abcd">` becomes
`<a href="unsafe:/1234abcd">`

😿

**Comment by nozer** [comment]
Pushed a fix, Tag is v0.9.5
