### ISSUE TITLE
Custom Blots

### ISSUE THREAD

**Issue by buildAI** [nozer/quill-delta-to-html#3]
Hey I'm using this library and I'm trying to render with a custom blot which eventually adds a custom attribute. I was planning to do it from this line
[Pointer in library](https://github.com/nozer/quill-delta-to-html/blob/b377d235b9bc3f9485146641c8a3409ef94943f5/src/OpToHtmlConverter.ts#L178)

I'm planning to patch the code in the line indicated above. Is this fine or is there a better way to extend and use this library for custom blots.

**Comment by nozer** [comment]
Hi, I did not take custom blots into consideration when developing the library as I did not need it; I have not even studied structure for them. I guess your best move forward is to clone the project and add in any changes you need.

**Comment by buildAI** [comment]
@nozer thanks. Will close the issue then. I'll try to fork it and make changes
