### ISSUE TITLE
Add support of check lists

### ISSUE THREAD

**Issue by volser** [nozer/quill-delta-to-html#30]
Open quill and type `[]` or `[x]` to get check list. Could be checked and unchecked
`<ul data-checked="false"></ul>`, `<ul data-checked="true"></ul>`

**Comment by volser** [comment]
PR https://github.com/nozer/quill-delta-to-html/pull/31

**Comment by nozer** [comment]
Just merged; thanks a lot!

**Comment by nozer** [comment]
Hey, I got some warnings about package.lock file and reverted. Can you remove that file and also increase the test coverage to 100%? Thanks

**Comment by nozer** [comment]
Nevermind, I will do it :)

**Comment by nozer** [comment]
I updated the way list html is generated. For example, given these ops:
```
[
   {insert: "done"}, 
   {attributes: {list: "checked"}, insert: "↵"}, 
   {insert: "not done"}, 
   {attributes: {list: "unchecked"}, insert: "↵"}
]
```
They will produce this html:
```<ul><li data-checked="true">done</li><li data-checked="false">not done</li></ul>```

Adding `data-checked` attribute to `ul` causes all items to be checked or unchecked. `quill` makes different lists for checked and unchecked items; that is semantically wrong. One should be able to have one list (contained within one `ul` tag that has both checked and unchecked items)

**Comment by nozer** [comment]
It already is not because we have been generating properly nested lists (inner list is located inside the `li` element of the parent list) from the beginning.

**Comment by volser** [comment]
@nozer you can close this one, works fine, thanks
