### ISSUE TITLE
TypeError: Cannot read property of 'QuillDeltaToHtmlConverter' of undefined

### ISSUE THREAD

**Issue by alexjustesen** [nozer/quill-delta-to-html#35]
Just found this library and trying to implement it into a project. I'm using requireJS to load my js files and I'm getting the following error.

`Uncaught TypeError: Cannot read property 'QuillDeltaToHtmlConverter' of undefined at QuillDeltaToHtmlConverter.bundle.js:1178`

Here is how I am loading and running the script:

```javascript
require(['quill-delta-to-html'], function( QuillDeltaToHtmlConverter ) {
        // Get quill contents
        var delta = JSON.parse( $('input[name=league_description]').val() );

        // Log contents delta ops to console
        console.log( delta.ops );
        console.log( window.opts_ );

        // Convert quill ops delta to html
        var converter = new QuillDeltaToHtmlConverter( delta.ops, {} );
        var html = converter.convert();

        // Log html to console
        console.log(html);

        // Update converted view
        document.getElementById('league-description-view').innerHTML = html;
    });
```

Any help would be greatly appreciated, thanks.

**Comment by nozer** [comment]
I am not using require js so I won't be able to help you here. But you can include the browser bundle in your html file as `<script src="dist/browser/QuillDeltaToHtmlConverter.bundle.js"></script>` and converter will be available as `window.QuillDeltaToHtmlConverter`

**Comment by nozer** [comment]
Fixed and pushed as v0.9.8

**Comment by alexjustesen** [comment]
I'll test tonight, thanks for the quick reply.

**Comment by nozer** [comment]
Welcome. Please close the isssue if all is ok.

**Comment by alexjustesen** [comment]
Looks like that addressed the undefined type error, there is a constructor error that I'll create a separate ticket for.

**Comment by nozer** [comment]
require(['quill-delta-to-html'], function( QuillDeltaToHtmlConverter...  In here, constructor is available as QuillDeltaToHtmlConverter.QuillDeltaToHtmlConverter
