### ISSUE TITLE
Inline `code` swallows other inline elements

### ISSUE THREAD

**Issue by dcsaszar** [nozer/quill-delta-to-html#38]
Input: `[{"attributes":{"italic":true,"link":"#top","code":true},"insert":"Top"},{"insert":"\n"}]`

### Expected output
`<p><code><a href="#top"><em>Top</em></a></code></p>` (the nesting order may differ)
### Actual output

`<p><code>Top</code></p>`

**Comment by nozer** [comment]
Fixed and pushed with tag `v0.9.9`
