### ISSUE TITLE
Support for link `target` is broken 😿

### ISSUE THREAD

**Issue by dcsaszar** [nozer/quill-delta-to-html#39]
V 0.9.9

### Input
`[{"attributes":{"target":"_self","link":"#"},"insert":"Ok"},{"insert":"\n"}]'`

### Expected output
`<p><a href="#" target="_self">Ok</a></p>`

### Actual output
`<p><a href="#">Ok</a></p>`

**Comment by nozer** [comment]
I have removed target attribute for anchor links. I added it to readme file

**Comment by dcsaszar** [comment]
It‘s not a common use case, but I don‘t see a reason to forbid this. In the end it should be the editor‘s choice. Note that, in our UI, „no target“ is the default.

**Comment by nozer** [comment]
Then I guess we should allow it only if it is specified in the attributes of the relevant op and not use the one specified in the converter options, default or not. What do you think?

**Comment by dcsaszar** [comment]
That would work for our use case. But IMO it‘s ok to simplify the code, i.e. treat anchor links like all other links, because this is what Quill does by default.

**Comment by nozer** [comment]
Will do. Thank you

**Comment by nozer** [comment]
Fixed and pushed as tag `v0.9.11`
