### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by kasparkallas** [nozer/quill-delta-to-html#42]
This feature has been in the making for over a year and is available in various Quill 2.0 development releases.

https://github.com/quilljs/quill/issues/117

Until Quill's official 2.0 release, table support could be optionally enabled in this package? Any idea how much work would it be to implement it?

**Comment by nozer** [comment]
I will look into it when I have time; I really don't know how long it would take. 
Thank you for letting me know about the tables support.

**Comment by Akitha** [comment]
@nozer Any Updates

**Comment by nozer** [comment]
I have not started yet. I will when I can. Sorry for the delay

**Comment by Akitha** [comment]
@nozer Thanks let us know if any

**Comment by LucasvlLima** [comment]
@nozer any news about this change?

**Comment by nozer** [comment]
Oh god, I feel bad. I just don't know when. All I can say is that I will do it when I have free time for this. I just don't know when.

**Comment by volser** [comment]
https://github.com/nozer/quill-delta-to-html/pull/74

**Comment by nozer** [comment]
Added at tag `v0.11.0`. Thanks to @volser
