### ISSUE TITLE
Background Color Support

### ISSUE THREAD

**Issue by valentinbdv** [nozer/quill-delta-to-html#45]
It seems like quill-delta-to-html doesn't had the background color. 

I guess this would not be too complicated to had it as there is already the color which is working perfectly. 

This is the same logic but with the "background" attribute of the delta and it should set the "background-color" style of the node. 

Tell me if I can help. ;)

**Comment by nozer** [comment]
It does produce `background-color:...`. Given these ops:
```
[{insert: "cads f "}, {attributes: {background: "#e60000"}, insert: "fdfd"}, {insert: " fsd "}]
```
it produces this output
```
<p>cads f <span style="background-color:#e60000">fdfd</span> fsd </p>
```
Tell me how come you don't see it with an example? ;)

**Comment by valentinbdv** [comment]
Ok I have found the issue then.

I had set the allowBackgroundClasses to true which prevent the basic background color.

My bad.
