### ISSUE TITLE
Support for classless HTML

### ISSUE THREAD

**Issue by jwalton** [nozer/quill-delta-to-html#46]
Hey,

I'm using this library to convert a quill delta into a block of HTML, which I want to embed inside an email.  As such, a) I don't want to have any tags with classes, because not all email client support classes and b) in our product we let customers supply their own HTML header and footer, so it's not trivial for me to inject classes into the HTML `<head>` tag anyways.

So what I'd like is an option like `inlineStyles: true` which would generate something like:

```html
<span style="text-align: center">Blah</span>
```

instead of:

```html
<span class="ql-align-center">Blah</span>
```

So I was wondering if you were interested in a PR to do such a thing?

**Comment by bnlab** [comment]
Yes, very helpful.
Thanks.
