### ISSUE TITLE
image link delta is not properly converted as image link

### ISSUE THREAD

**Issue by rkdrnf** [nozer/quill-delta-to-html#53]
```
{ 
 attributes: {link: "https://quilljs.com"}
 insert: {image: "/img/fileIcon.png"}
}
```
delta like above is not properly converted to image link.
Though it's a way to make image link presented in quilljs.com

**Comment by nozer** [comment]
Hi
Thanks for the bug report. I have just fixed and pushed with tag `v0.10.7`
