### ISSUE TITLE
<img> tag may need to be placed in a different group

### ISSUE THREAD

**Issue by sunjoong85** [nozer/quill-delta-to-html#54]
A plain text and image is placed in a same group. Is there a way to make img tag is wrapped with single wrapper such as P or DIV without any siblings?
Great works. Thanks.

**Comment by nozer** [comment]
There is no way to do that currently. However, you can put it inside one of those block elements (direction, alignment, indent, block quote, header). For example, you can select the image and click on `H1` and it will put the image in an `<h1>` tag.
