### ISSUE TITLE
HTML to Delta?

### ISSUE THREAD

**Issue by skela** [nozer/quill-delta-to-html#56]
Is there any support to convert html to delta?

If not do you have any ideas, or tips to achieve that?

I've found this library here: https://github.com/joelcolucci/node-quill-converter but its only for node applications :(

**Comment by KenanSulayman** [comment]
`(new Quill(document.createElement('div'))).clipboard.convert(html);`

**Comment by nozer** [comment]
Hi @skela 
Unfortunately, I don't at this moment and have not explored that avenue. I think suggestion of @KenanSulayman is a great way to achieve that.
