### ISSUE TITLE
Support for rendering direct to react?

### ISSUE THREAD

**Issue by andrewphillipoef** [nozer/quill-delta-to-html#57]
Would be cool if this could output React instead of HTML as I will have to process the out from this into react rather than use __dangerousSetInnnerHtml

**Comment by nozer** [comment]
Yes it would be great but I don't have time to do it at this point. Sorry :(

**Comment by vanoop729** [comment]
Hey @nozer How to display the `var html = converter.convert();` in react? It just displays as a string for me.
