### ISSUE TITLE
Support for Quill Mention

### ISSUE THREAD

**Issue by unitehenry** [nozer/quill-delta-to-html#63]
I had written a custom blot handler to support the ```DOMStringMap``` object that [quill-mention](https://github.com/afconsult/quill-mention) uses to render their mentions.

```js
      // Custom Blot Handler
      converter.renderCustomWith((customOp) => {
        // Conditionally renders blot of mention type
        if(customOp.insert.type === 'mention'){
          // Get Mention Blot Data
          const mention = customOp.insert.value;

          // Template Return Data
          return (
            `
            <span
              class="mention"
              data-index="${mention.index}"
              data-denotation-char="${mention.denotationChar}"
              data-key="${mention.key}"
              data-link="${mention.link}"
              data-value='${mention.value}'
            >﻿
              <span contenteditable="false">
                ${mention.value}
              </span>
            ﻿</span>
            `
          )
        }
      })
```

Maybe we can add a way to render this as html. I'm not too sure how the current mention support works, but maybe we can build on top of that. Regardless, I could just be missing something and there already is support for this.

**Comment by nozer** [comment]
Hi

What you are doing is fine and it should be the way forward. 

This library goal is to only support core quilts deltas and not also community provided module deltas as well. 

So, I would like to stick to supporting generation of html from only core quillljs deltas. For all others, `renderCustomWith` method should be used. I know there is a mention support that was added as a result of the pull request from someone, but I felt bad about rejecting a pull request and didn't think about its consequences (This is my first public library and I learned late that I shouldn't try to please everyone). I will be deprecating and removing existing mention support in favor of using `renderCustomWith` in the future.

**Comment by unitehenry** [comment]
Ok thanks for the response and thank you for maintaining the project.

**Comment by DeeTheDev** [comment]
@unitehenry You are a life saver. ❤️
