### ISSUE TITLE
Custom inline blot missed by renderCustomWith()

### ISSUE THREAD

**Issue by Gladskih** [nozer/quill-delta-to-html#68]
There is a simple example of extending Quill with mark tag support like so:
```
class MarkBlot extends Quill.import('blots/inline') { } 
MarkBlot.blotName = 'mark';
MarkBlot.tagName = 'mark'; 
Quill.register(MarkBlot);
```

It can make Quill produce a delta like:
`{"ops":[{"attributes":{"mark":true},"insert":"q"},{"insert":"\n"}]}`

Then in accordance with your guide a do:
```
converter.renderCustomWith((customOp, contextOp) =>
	customOp.insert.type === 'mark' ?
		`<mark>${customOp.insert.value.text}</mark>`
		: 'Unmanaged custom blot!';
```
But passed function doesn't even called!
What's wrong?

**Comment by volser** [comment]
renderCustomWith works only for embed blots (

**Comment by Gladskih** [comment]
@volser But EmbedBlot is an abstraction of Parchment as Quilljs data model. Quill-delta-to-html works with Delta which has no relation to Parchment by itself.

Does Quill-delta-to-html depend on  Parchment somehow?

**Comment by Gladskih** [comment]
And I know it's related to https://github.com/nozer/quill-delta-to-html/issues/55#issue-407427341
But I do not know how to make Quill create custom op instead of attribute. And I doubd it's right way to  fix the flaw.

**Comment by volser** [comment]
pushed version with new features
