### ISSUE TITLE
Module build failed: TypeError: Path must be a string. Received [Function]

### ISSUE THREAD

**Issue by LaveyD** [nozer/quill-delta-to-html#9]
Hi. After I import this module, error happens when webpack build as bellow: 

`Module build failed: TypeError: Path must be a string. Received [Function]
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:346:5)
    at normalizePaths (F:\DevCenter\node_modules\stylus-loader\lib\pathcache.js:301:21)
    at stylusFile (F:\DevCenter\node_modules\stylus-loader\lib\pathcache.js:102:14)
    at F:\DevCenter\node_modules\stylus-loader\lib\pathcache.js:159:32`

there should has some conflict with webpack or stylus-loader,  but i have no idea about it, could you help and give some advice pls?
node version: v8.9.3 npm version: 5.6.0  webpack version: 3.0.0 stylus-loader version: 3.0.1
Thanks very much!

**Comment by nozer** [comment]
I just built distribution code and pushed with tag `v0.5.4`. You may pull the latest and try again. I am not sure if that was the issue though.

**Comment by LaveyD** [comment]
@nozer Thanks for your update, but the problem still exsits.

**Comment by nozer** [comment]
Can you show some code; like how you are importing it?

**Comment by LaveyD** [comment]
OK. I'll prepare the code then. ^^
